# Materials Project - Structure Database
name: Materials Project  
description: Fetch crystal structures and properties

# What users might say -> What to do
understands:
  fetch:
    aliases: [get, download, pull, materials project]
    action: fetch_structure
    
  search:
    aliases: [find, query, look for]
    action: search_materials

# What to extract
extracts:
  material_id:
    keywords: [mp-, mp]
    examples:
      - "mp-149 -> mp-149"
      - "mp149 -> mp-149"
    required: true
    
  material_name:
    # Common materials shortcuts
    shortcuts:
      silicon: mp-149
      si: mp-149
      graphene: mp-1040425
      diamond: mp-66
      gan: mp-804
      gaas: mp-2534
      
  properties:
    keywords: [band gap, formation energy, elastic, structure]
    examples:
      - "band gap -> [band_gap]"
      - "all properties -> [structure, band_gap, formation_energy]"
    default: [structure, formula, band_gap]

# API settings
api:
  key: $MP_API_KEY  # from environment
  cache: true

# What we create
creates:
  structure:
    type: System
    from: api.structure
    
  properties:
    type: Artifact
    from: api.properties