# VASP - Vienna Ab initio Simulation Package
name: VASP
description: First-principles electronic structure calculations

# What users say -> What we do
understands:
  dft:
    aliases: [density functional, ab initio, first principles]
    method: single_point
    
  band structure:
    aliases: [bands, electronic structure, band gap]
    method: band_structure
    
  relaxation:
    aliases: [optimize, relax, geometry optimization]
    method: geometry_opt

# Extract from user input
extracts:
  functional:
    keywords: [pbe, lda, hse, gga]
    examples:
      - "use PBE -> PBE"
      - "HSE06 functional -> HSE06"
    default: PBE
    
  cutoff:
    keywords: [eV, cutoff, encut]
    examples:
      - "500 eV cutoff -> 500"
      - "encut 520 -> 520"
    default: 520
    
  k_points:
    keywords: [kpoints, k-points, mesh]
    examples:
      - "5x5x5 k-points -> [5, 5, 5]"
      - "gamma centered -> gamma"
    default: [4, 4, 4]

# How to run
runs_with:
  local: /opt/vasp/bin/vasp_std
  
# Input generation
generates:
  single_point:
    needs: [structure]
    files:
      INCAR: |
        SYSTEM = {material}
        ENCUT = {cutoff}
        GGA = {functional}
        ISMEAR = 0
        SIGMA = 0.05
      
  geometry_opt:
    needs: [structure]
    files:
      INCAR: |
        SYSTEM = {material}
        ENCUT = {cutoff}
        IBRION = 2
        ISIF = 3
        NSW = 100
        EDIFFG = -0.01

# Output parsing
parses:
  single_point:
    file: OUTCAR
    gets:
      - total_energy
      - band_gap
      - fermi_level